export const surpriseMePrompts = [
    'A vintage carousel with unicorns instead of horses, surrounded by candy clouds and rainbow skies',
    'A futuristic underwater library filled with glowing jellyfish, where mermaids read books by bioluminescent light.',
    'Hello Kitty hosting a tea party in a Victorian-era garden, surrounded by whimsical topiaries and blooming flowers.',
    'A steam-powered dirigible flying over a medieval cityscape, casting shadows on cobblestone streets below.',
    'A cyberpunk cityscape where cats ride hoverboards and play electric guitars on neon-lit rooftops.',
    'A haunted mansion guarded by robotic gargoyle sentinels, with holographic ghosts floating around the turrets.',
    'A portrait of a time-traveling flamingo explorer discovering a hidden jungle temple filled with glowing treasures.',
    'A magical forest where fireflies and lantern bugs illuminate the path of a wandering fox in a cloak.',
    'A steampunk tea party hosted by mechanical rabbits in an enchanted clock tower garden.',
    'An enchanted bakery where gingerbread people come to life and dance under the light of sugary chandeliers.',
    'A celestial garden floating in space, with crystalline flowers and planets as stepping stones.',
    'A dreamy sky filled with flying whales and giant floating islands made of fluffy cotton candy.',
    'A lunar base built entirely of crystalline structures, reflecting the light of a nearby Earth.',
    'A haunted shipwreck at the bottom of the ocean, with ghostly sailors and shimmering underwater flora.',
    'A cozy hobbit hole nestled in a technicolor mushroom forest, with tiny bioluminescent critters.',
    'A futuristic cityscape where skyscrapers are shaped like giant musical instruments, emitting harmonious sounds.',
    'A cybernetic jungle where robotic monkeys swing from digital vines, surrounded by holographic butterflies.',
    'A celestial bazaar on a moonlit asteroid, where aliens barter under a sky filled with shooting stars.',
    'A carnival of floating islands, where gravity is optional and roller coasters loop through the clouds.',
    'A hidden garden of glowing crystals, tended by a gnome-like creature made of stardust.',
    'A magical mirror that reveals different dimensions with each reflection, showing fantastical landscapes.',
    'A dragon-themed water park with slides made of rainbow-colored scales and pools shaped like dragon eggs.',
    'A library of living books, where characters jump off the pages and act out their stories.',
    'A time-traveling train station with steam-powered locomotives departing to different eras.',
    'A steampunk masquerade ball attended by clockwork automatons and elegant aristocrats in masks.',
    'An enchanted forest where trees sing and dance to the rhythm of the wind, surrounded by firefly fairies.',
    'A secret garden hidden behind a waterfall, with glowing flowers and whimsical creatures.',
    'A cosmic ice cream parlor where planets are scoops of ice cream and asteroids are sprinkles.',
    'A floating city of airships and hot air balloons, bustling with merchants and travelers from different worlds.',
    'A magical academy in the clouds, where students learn to control weather and create constellations.',
    'A time-traveling cat exploring ancient Egyptian pyramids, surrounded by hieroglyphic puzzles.',
    'A cybernetic rainforest with robotic creatures and neon foliage, illuminated by digital rain.',
    'A floating marketplace of bioluminescent jellyfish vendors selling sparkling sea treasures.',
    'A psychedelic desert oasis with neon cacti and sand dunes that shift like waves.',
    'An underwater circus with acrobatic clownfish, musical starfish, and dancing octopuses.',
    'A futuristic art gallery filled with interactive holographic sculptures and paintings that come to life.',
    'A celestial chessboard where planets and stars replace traditional chess pieces.',
    'A mythical creature sanctuary where griffins, unicorns, and phoenixes roam freely among ancient ruins.',
    'A cosmic roller coaster that twists and turns through the aurora borealis, creating mesmerizing light trails.',
    'A pirate ship crewed by whimsical creatures like octopus pirates and parrot mermaids.',
    'A neon-lit dance club on the moon, where aliens and astronauts groove to synthwave beats.',
    'A cyberpunk jungle where robotic toucans and chameleons blend into the glowing foliage.',
    'A bustling steampunk marketplace with mechanical street performers and steam-powered carousels.',
    'A secret garden hidden within an abandoned clock tower, filled with gears and ticking timepieces.',
    'A floating observatory where astronomers study cosmic phenomena from a vantage point among the stars.',
    'A fantastical race of clockwork dragons soaring through the skies of a steampunk city.',
    'A holographic safari where visitors can interact with lifelike digital representations of extinct animals.',
    'A magical cafe where patrons sip potions that change their appearance and abilities.',
    'A crystal cavern filled with shimmering stalactites and stalagmites, illuminated by glowing crystals.',
    'A mythical underwater kingdom ruled by a narwhal queen and her court of merfolk and sea creatures.'
];